language: objective-c
os: osx
osx_image: xcode8.1

git:
  depth: 3

branches:
  only:
  - master

xcode_project: MIPSCPU.xcodeproj
xcode_scheme: MIPSCPU

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool