language: objective-c
os: osx
osx_image: xcode8.2

git:
  depth: 3

branches:
  only:
    - master

xcode_project: MIPSCPU.xcodeproj
xcode_scheme: MIPSCPU

before_install:
  - gem install xcpretty
  - gem install xcpretty-travis-formatter

script:
  - xcodebuild -project MIPSCPU.xcodeproj -scheme MIPSCPU build | xcpretty -f `xcpretty-travis-formatter`
