language: c

branches:
  only:
    - master

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      gem install xcpretty;
      gem install xcpretty-travis-formatter;
    fi

jobs:
  include:
    - os: osx
      osx_image: xcode12.4
      env: BUILD_TYPE=xcode
    - os: osx
      osx_image: xcode12.4
      compiler: clang
      env: BUILD_TYPE=cmake COMPILER=clang++ C_COMPILER=clang -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
    - os: linux
      dist: trusty
      services:
        - docker
      env: BUILD_TYPE=docker

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - if [[ "$BUILD_TYPE" == "cmake" ]]; then export PATH=${TRAVIS_BUILD_DIR}/HopperSDK-v4/Linux/gnustep-Linux-x86_64/bin/:$PATH ; fi

script:
  - if [[ "$BUILD_TYPE" == "xcode" ]]; then xcodebuild -project MIPSCPU.xcodeproj -scheme MIPSCPUTests test | xcpretty -f `xcpretty-travis-formatter`; fi
  - if [[ "$BUILD_TYPE" == "xcode" ]]; then xcodebuild -project MIPSCPU.xcodeproj -scheme MIPSCPU build | xcpretty -f `xcpretty-travis-formatter`; fi
  - if [[ "$BUILD_TYPE" == "cmake" ]]; then ./build.sh; fi
  - if [[ "$BUILD_TYPE" == "docker" ]]; then ./docker/linux-build.sh; fi
