language: c
dist: trusty
sudo: false

git:
  depth: 3

branches:
  only:
    - master

cache:
  apt: true
  directories:
    - $HOME/GNUstep/Library/ApplicationSupport/Hopper/gnustep-x86_64/

addons:
  apt:
    packages:
      - libpthread-workqueue-dev
      - libkqueue-dev
      - libblocksruntime-dev
      - libxml2-dev
      - libxslt1-dev
      - clang-4.0
    sources:
      - llvm-toolchain-trusty-4.0

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew upgrade; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      gem install xcpretty;
      gem install xcpretty-travis-formatter;
      xcodebuild -project MIPSCPU.xcodeproj -list;
    fi
  - if [[ $TRAVIS_OS_NAME == 'linux' && ! -e $HOME/GNUstep/Library/ApplicationSupport/Hopper/gnustep-x86_64/bin/gnustep-config ]]; then
      echo "Building GNUstep.";
      git clone https://github.com/ckuethe/HopperSDK-Linux.git;
      cd HopperSDK-Linux;
      sed -i -e '27,34d' install.sh;
      ./install.sh;
    else
      echo "Skipping GNUstep build.";
    fi

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      env: BUILD=xcode
    - os: osx
      osx_image: xcode8.3
      env: BUILD=cmake
    - os: linux
      compiler: clang-4.0
      env: BUILD=cmake

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - if [[ "$BUILD" == "cmake" ]]; then export PATH=$HOME/GNUstep/Library/ApplicationSupport/Hopper/gnustep-x86_64/bin/:$PATH ; fi

script:
  - if [[ "$BUILD" == "xcode" ]]; then xcodebuild -project MIPSCPU.xcodeproj build | xcpretty -f `xcpretty-travis-formatter`; fi
  - if [[ "$BUILD" == "cmake" ]]; then
      if [[ $TRAVIS_OS_NAME == 'linux' ]]; then export CC=clang-4.0 CXX=clang++-4.0; fi;
      cmake . -Bbuild;
    fi
  - if [[ "$BUILD" == "cmake" ]]; then cmake --build build -- ; fi
